# Generated by Django 5.1.1 on 2024-09-13 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abrigo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abrigo',
            name='cidade',
            field=models.CharField(default='Descohecida', max_length=100),
            preserve_default=False,
        ),
    ]
