# Generated by Django 5.1.1 on 2024-09-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abrigo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raca', models.CharField(blank=True, max_length=50, null=True)),
                ('idade', models.IntegerField()),
                ('porte', models.CharField(max_length=20)),
                ('cor', models.CharField(blank=True, max_length=30, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_animais/')),
                ('data_resgate', models.DateField(auto_now_add=True)),
                ('adotado', models.BooleanField(default=False)),
                ('abrigo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abrigo.abrigo')),
            ],
        ),
    ]
