# Generated by Django 5.1.1 on 2024-09-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adotante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adocao', models.DateField(auto_now=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adotante.adotante')),
            ],
        ),
    ]
