# Generated by Django 5.1.1 on 2024-09-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adocao', '0001_initial'),
        ('animal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adocao',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animal.animal'),
        ),
    ]
